version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: nearmate-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nearmateadmin
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  adminer:
    image: adminer
    container_name: nearmate-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  mysql_data:


